/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system_football_management;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author KELOMPOK PBO :
 * - CHOKY ANDRIANO
 * - ZAINI MUHTAROM
 * - ALVIAN SAPUTRA PRATAMA
 * - DENIS ALVIANSYAH
 */
public class Fixture extends javax.swing.JFrame {

    /**
     * Creates new form Club
     */
    
    private void Kosongkan_Form() {
        txt_home.setEditable(true);
        txt_no.setText(null);
        combo_week.setSelectedItem(null);
        txt_home.setText(null);
        txt_away.setText(null);
        combo_leg.setSelectedItem(null);
        combo_day.setSelectedItem(null);
        txt_clock.setText(null);
        
    }
    
    public Fixture() {
        initComponents();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        subject = new javax.swing.JLabel();
        Club_name = new javax.swing.JLabel();
        txt_home = new javax.swing.JTextField();
        Match_Win = new javax.swing.JLabel();
        No = new javax.swing.JLabel();
        txt_away = new javax.swing.JTextField();
        txt_no = new javax.swing.JTextField();
        Group2 = new javax.swing.JLabel();
        worldcup = new javax.swing.JLabel();
        combo_leg = new javax.swing.JComboBox<>();
        Days = new javax.swing.JLabel();
        combo_day = new javax.swing.JComboBox<>();
        combo_week = new javax.swing.JComboBox<>();
        MatchLeg1 = new javax.swing.JLabel();
        FixtureWeek1 = new javax.swing.JLabel();
        txt_clock = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        subject2 = new javax.swing.JLabel();
        save_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabListGroup = new javax.swing.JTable();
        reset_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        fifa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subject.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 24)); // NOI18N
        subject.setText("FOOTBALL MANAGEMENT");
        jPanel1.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        Club_name.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        Club_name.setForeground(new java.awt.Color(255, 255, 255));
        Club_name.setText("CLUB HOME");
        jPanel1.add(Club_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txt_home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_homeActionPerformed(evt);
            }
        });
        jPanel1.add(txt_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 200, -1));

        Match_Win.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        Match_Win.setForeground(new java.awt.Color(255, 255, 255));
        Match_Win.setText("CLUB AWAY");
        jPanel1.add(Match_Win, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        No.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        No.setForeground(new java.awt.Color(255, 255, 255));
        No.setText("MATCH");
        jPanel1.add(No, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        txt_away.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_away.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_awayActionPerformed(evt);
            }
        });
        jPanel1.add(txt_away, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 200, -1));

        txt_no.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noActionPerformed(evt);
            }
        });
        jPanel1.add(txt_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, 30));

        Group2.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        Group2.setForeground(new java.awt.Color(255, 255, 255));
        Group2.setText("O'CLOCK");
        jPanel1.add(Group2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        worldcup.setBackground(new java.awt.Color(52, 73, 94));
        worldcup.setFont(new java.awt.Font("Lucida Handwriting", 3, 18)); // NOI18N
        worldcup.setText("For The Good Of The Game ");
        jPanel1.add(worldcup, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        combo_leg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LEG 1", "LEG 2" }));
        jPanel1.add(combo_leg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 110, 30));

        Days.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        Days.setForeground(new java.awt.Color(255, 255, 255));
        Days.setText("DAYS");
        jPanel1.add(Days, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        combo_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15 FEBRUARY 2023", "16 FEBRUARY 2023", "22 FEBRUARY 2023", "23 FEBRUARY 2023", " ", " " }));
        jPanel1.add(combo_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 150, 30));

        combo_week.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIRST WEEK", "SECOND WEEK" }));
        jPanel1.add(combo_week, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 130, 30));

        MatchLeg1.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        MatchLeg1.setForeground(new java.awt.Color(255, 255, 255));
        MatchLeg1.setText("MATCH LEG");
        jPanel1.add(MatchLeg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        FixtureWeek1.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        FixtureWeek1.setForeground(new java.awt.Color(255, 255, 255));
        FixtureWeek1.setText("FIXTURE WEEK ");
        jPanel1.add(FixtureWeek1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        txt_clock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_clock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_clockActionPerformed(evt);
            }
        });
        jPanel1.add(txt_clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 100, 30));

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZAINI M\\Pictures\\New Folder\\d59b58942a3765028b41c0bc806be6ae.jpg")); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, 0, 690, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));

        jPanel2.setBackground(new java.awt.Color(130, 204, 221));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        jPanel2.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 320, 30));

        search_btn.setBackground(new java.awt.Color(149, 165, 166));
        search_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        search_btn.setForeground(new java.awt.Color(255, 255, 255));
        search_btn.setText("SEARCH");
        search_btn.setBorder(null);
        search_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_btnMouseClicked(evt);
            }
        });
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        jPanel2.add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, 30));

        update_btn.setBackground(new java.awt.Color(149, 165, 166));
        update_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        update_btn.setForeground(new java.awt.Color(255, 255, 255));
        update_btn.setText("UPDATE");
        update_btn.setBorder(null);
        update_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel2.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 90, 30));

        delete_btn.setBackground(new java.awt.Color(149, 165, 166));
        delete_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setText("DELETE");
        delete_btn.setBorder(null);
        delete_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_btnMouseClicked(evt);
            }
        });
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel2.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 90, 30));

        subject2.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 30)); // NOI18N
        subject2.setForeground(new java.awt.Color(255, 255, 255));
        subject2.setText("FIXTURE UPDATE OF ROUND 16");
        jPanel2.add(subject2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, 30));

        save_btn.setBackground(new java.awt.Color(149, 165, 166));
        save_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        save_btn.setForeground(new java.awt.Color(255, 255, 255));
        save_btn.setText("SAVE");
        save_btn.setBorder(null);
        save_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        jPanel2.add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 90, 30));

        TabListGroup.setAutoCreateRowSorter(true);
        TabListGroup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TabListGroup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        TabListGroup.setAutoscrolls(false);
        TabListGroup.setDragEnabled(true);
        TabListGroup.setGridColor(new java.awt.Color(0, 0, 0));
        TabListGroup.setShowGrid(true);
        TabListGroup.setSurrendersFocusOnKeystroke(true);
        TabListGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabListGroupMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabListGroup);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 960, 200));

        reset_btn.setBackground(new java.awt.Color(149, 165, 166));
        reset_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        reset_btn.setForeground(new java.awt.Color(255, 255, 255));
        reset_btn.setText("RESET");
        reset_btn.setBorder(null);
        reset_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_btnMouseClicked(evt);
            }
        });
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        jPanel2.add(reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 90, 30));

        back_btn.setBackground(new java.awt.Color(149, 165, 166));
        back_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setText("BACK");
        back_btn.setBorder(null);
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel2.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 550, 80, 30));

        fifa.setBackground(new java.awt.Color(52, 73, 94));
        fifa.setFont(new java.awt.Font("Lucida Handwriting", 3, 18)); // NOI18N
        fifa.setForeground(new java.awt.Color(255, 255, 255));
        fifa.setText("Uefa Champions League 2022 - 2023");
        jPanel2.add(fifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 410, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 990, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private DefaultTableModel tableModel;
    private ResultSet resultSet;
    public final void showTable(){
        try {
            Connection conn = ConnectionDatabase.configDB();
            
            Object[] columnTitle = {"MATCH","FIXTURE WEEK","CLUB HOME","CLUB AWAY","LEG","DAYS","CLOCK"};
            tableModel = new DefaultTableModel(null,columnTitle);
            TabListGroup.setModel(tableModel);
            Statement statement = conn.createStatement();
            tableModel.getDataVector().removeAllElements();
            
            resultSet = statement.executeQuery("SELECT * FROM name_fixture");
            while(resultSet.next()){
                Object[] data = {
                    resultSet.getString("NO"),
                    resultSet.getString("WEEK"),
                    resultSet.getString("CLUB_HOME"),
                    resultSet.getString("CLUB_AWAY"),
                    resultSet.getString("LEG"),
                    resultSet.getString("DAY"),
                    resultSet.getString("CLOCK")
                        
                };
                tableModel.addRow(data);
            }
            System.out.println("");
            
        } catch (SQLException e) {
            System.out.println("NOT FOUND DATA !");
            System.out.println(e);
        }
    }
    private final String regex = "\\s";
    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        try {
            String Match = txt_no.getText();
            String Week = (String)combo_week.getSelectedItem();
            String Home = txt_home.getText();
            String Away= txt_away.getText();
            String Leg = (String)combo_leg.getSelectedItem();
            String Day = (String)combo_day.getSelectedItem();
            String Clock = txt_clock.getText();
            System.out.println(Away.matches(regex));
            if ((Week.isEmpty()||Week.length()<3)||(Home.isEmpty()||Home.matches(regex))||(Away.isEmpty()||Home.matches(regex))||(Away.isEmpty()||Away.matches(regex))||(Leg.isEmpty())||Leg.matches(regex)||(Day.isEmpty())||Day.matches(regex)||(Clock.isEmpty())||Clock.matches(regex)||(Match.isEmpty())||Match.matches(regex)){
                JOptionPane.showMessageDialog(null, "DATA INVALID","Failed",JOptionPane.ERROR_MESSAGE);
            
            }else{
                String sql = "INSERT INTO `name_fixture`(`WEEK`, `CLUB_HOME`, `CLUB_AWAY`, `LEG`, `DAY`, `CLOCK`) VALUES ('"+combo_week.getSelectedItem()+"','"+txt_home.getText()+"','"+txt_away.getText()+"','"+combo_leg.getSelectedItem()+"','"+combo_day.getSelectedItem()+"','"+txt_clock.getText()+ "')";
                Connection conn = ConnectionDatabase.configDB();
                PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                showTable();
                JOptionPane.showMessageDialog(null, "DATA SAVED SUCESSFULLY");
                Kosongkan_Form(); 
            }
                    
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showConfirmDialog(this, e.getMessage());       
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_delete_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        try {
            String Match = txt_no.getText();
            String Week = (String)combo_week.getSelectedItem();
            String Home = txt_home.getText();
            String Away= txt_away.getText();
            String Leg = (String)combo_leg.getSelectedItem();
            String Day = (String)combo_day.getSelectedItem();
            String Clock = txt_clock.getText();
            System.out.println(Away.matches(regex));
            if ((Week.isEmpty()||Week.length()<3)||(Home.isEmpty()||Home.matches(regex))||(Away.isEmpty()||Home.matches(regex))||(Away.isEmpty()||Away.matches(regex))||(Leg.isEmpty())||Leg.matches(regex)||(Day.isEmpty())||Day.matches(regex)||(Clock.isEmpty())||Clock.matches(regex)||(Match.isEmpty())||Match.matches(regex)){
                JOptionPane.showMessageDialog(null, "DATA INVALID","Failed",JOptionPane.ERROR_MESSAGE);
                
        }else {
            String sql = "UPDATE `name_fixture` SET `WEEK`='"+combo_week.getSelectedItem()+"',`CLUB_HOME`='"+txt_home.getText()+"',`CLUB_AWAY`='"+txt_away.getText()+"',`LEG`='"+combo_leg.getSelectedItem()+"',`DAY`='"+combo_day.getSelectedItem()+"',`CLOCK`='"+txt_clock.getText()+"' WHERE NO='"+txt_no.getText()+"'";
            Connection conn = ConnectionDatabase.configDB();
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            showTable();
            JOptionPane.showMessageDialog(null, "DATA EDITED SUCCESFULLY"); 
            }
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }            
    }//GEN-LAST:event_update_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_btnActionPerformed

    private void txt_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_homeActionPerformed

    private void txt_awayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_awayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_awayActionPerformed

    private void search_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_btnMouseClicked
        // TODO add your handling code here:
        try {
            Connection conn = ConnectionDatabase.configDB();
            
            Object[] columnTitle = {"MATCH","FIXTURE WEEK","CLUB HOME","CLUB AWAY","LEG","DAYS","CLOCK"};
            tableModel = new DefaultTableModel(null,columnTitle);
            TabListGroup.setModel(tableModel);
            Statement statement = conn.createStatement();
            tableModel.getDataVector().removeAllElements();
            
            resultSet = statement.executeQuery("SELECT * FROM `name_fixture` WHERE CLUB_HOME LIKE '%" + txt_search.getText() + "%'");
            int i = 1;
            while(resultSet.next()){
                Object[] data = {
                    resultSet.getString("NO"),
                    resultSet.getString("WEEK"),
                    resultSet.getString("CLUB_HOME"),
                    resultSet.getString("CLUB_AWAY"),
                    resultSet.getString("LEG"),
                    resultSet.getString("DAY"),
                    resultSet.getString("CLOCK")
                        
                };
                tableModel.addRow(data);
            }   
        } catch (SQLException e) {
            System.out.println("NOT FOUND DATA !");
            System.out.println(e);
        }
    
    }//GEN-LAST:event_search_btnMouseClicked

    private void reset_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_btnMouseClicked
        // TODO add your handling code here:
        Kosongkan_Form();
    }//GEN-LAST:event_reset_btnMouseClicked

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reset_btnActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void TabListGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabListGroupMouseClicked
        // TODO add your handling code here:
        int baris = TabListGroup.rowAtPoint(evt.getPoint());
        
        String no = TabListGroup.getValueAt(baris, 0).toString();
        txt_no.setText(no);
        
        String week = TabListGroup.getValueAt(baris, 1).toString();
        combo_week.setSelectedItem(week);
        
        String clubhome = TabListGroup.getValueAt(baris, 2).toString();
        txt_home.setText(clubhome);
        
        String clubaway = TabListGroup.getValueAt(baris, 3).toString();
        txt_away.setText(clubaway);
        
        String leg = TabListGroup.getValueAt(baris, 4).toString();
        combo_leg.setSelectedItem(leg);
        
        String days = TabListGroup.getValueAt(baris, 5).toString();
        combo_day.setSelectedItem(days);
        
        String clock = TabListGroup.getValueAt(baris, 6).toString();
        txt_clock.setText(clock);
        
       
        
        
       
        
    }//GEN-LAST:event_TabListGroupMouseClicked

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Home n = new Home();
        n.setVisible(true);
    }//GEN-LAST:event_back_btnMouseClicked

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_back_btnActionPerformed

    private void txt_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noActionPerformed

    private void delete_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_btnMouseClicked
        // TODO add your handling code here:
        try {
            String Match = txt_no.getText();
            String Week = (String)combo_week.getSelectedItem();
            String Home = txt_home.getText();
            String Away= txt_away.getText();
            String Leg = (String)combo_leg.getSelectedItem();
            String Day = (String)combo_day.getSelectedItem();
            String Clock = txt_clock.getText();
            System.out.println(Away.matches(regex));
            if ((Week.isEmpty()||Week.length()<3)||(Home.isEmpty()||Home.matches(regex))||(Away.isEmpty()||Home.matches(regex))||(Away.isEmpty()||Away.matches(regex))||(Leg.isEmpty())||Leg.matches(regex)||(Day.isEmpty())||Day.matches(regex)||(Clock.isEmpty())||Clock.matches(regex)||(Match.isEmpty())||Match.matches(regex)){
                JOptionPane.showMessageDialog(null, "DATA INVALID","Failed",JOptionPane.ERROR_MESSAGE);
                
       } else {
            String sql = "DELETE FROM `name_fixture` WHERE CLUB HOME='"+ txt_home.getText() + "'";
            Connection conn = ConnectionDatabase.configDB();
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            showTable();
            JOptionPane.showMessageDialog(null, "DATA DELETED SUCCESFULLY");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        showTable();
        Kosongkan_Form();
    }//GEN-LAST:event_delete_btnMouseClicked

    private void txt_clockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_clockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_clockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fixture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fixture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fixture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fixture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fixture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Club_name;
    private javax.swing.JLabel Days;
    private javax.swing.JLabel FixtureWeek1;
    private javax.swing.JLabel Group2;
    private javax.swing.JLabel MatchLeg1;
    private javax.swing.JLabel Match_Win;
    private javax.swing.JLabel No;
    private javax.swing.JTable TabListGroup;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox<String> combo_day;
    private javax.swing.JComboBox<String> combo_leg;
    private javax.swing.JComboBox<String> combo_week;
    private javax.swing.JButton delete_btn;
    private javax.swing.JLabel fifa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JLabel subject;
    private javax.swing.JLabel subject2;
    private javax.swing.JTextField txt_away;
    private javax.swing.JTextField txt_clock;
    private javax.swing.JTextField txt_home;
    private javax.swing.JTextField txt_no;
    private javax.swing.JTextField txt_search;
    private javax.swing.JButton update_btn;
    private javax.swing.JLabel worldcup;
    // End of variables declaration//GEN-END:variables
}
