/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system_football_management;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author KELOMPOK PBO :
 * - CHOKY ANDRIANO
 * - ZAINI MUHTAROM
 * - ALVIAN SAPUTRA PRATAMA
 * - DENIS ALVIANSYAH
 */
public class Superstar extends javax.swing.JFrame {

    /**
     * Creates new form Superstar
     */
    private void Kosongkan_Form() {
        txt_no.setEditable(true);
        txt_no.setText(null);
        txt_club.setText(null);
        txt_nameplayer.setText(null);
        txt_nationality.setText(null);
        txt_ageplayer.setText(null);
        txt_number.setText(null);
        txt_position.setText(null);
        txt_search.setText(null);
    }
    public Superstar() {
        initComponents();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_search = new javax.swing.JTextField();
        reset_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        subject2 = new javax.swing.JLabel();
        worldcup = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabListPlayer = new javax.swing.JTable();
        Name_Player = new javax.swing.JLabel();
        txt_nameplayer = new javax.swing.JTextField();
        No = new javax.swing.JLabel();
        txt_number = new javax.swing.JTextField();
        NumberShirt = new javax.swing.JLabel();
        txt_nationality = new javax.swing.JTextField();
        Age = new javax.swing.JLabel();
        txt_club = new javax.swing.JTextField();
        Nationality = new javax.swing.JLabel();
        search_btn = new javax.swing.JButton();
        txt_no = new javax.swing.JTextField();
        Position = new javax.swing.JLabel();
        txt_ageplayer = new javax.swing.JTextField();
        Club_name1 = new javax.swing.JLabel();
        txt_position = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 320, 30));

        reset_btn.setBackground(new java.awt.Color(44, 58, 71));
        reset_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        reset_btn.setForeground(new java.awt.Color(255, 255, 255));
        reset_btn.setText("RESET");
        reset_btn.setBorder(null);
        reset_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_btnMouseClicked(evt);
            }
        });
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        getContentPane().add(reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 100, 40));

        delete_btn.setBackground(new java.awt.Color(44, 58, 71));
        delete_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setText("DELETE");
        delete_btn.setBorder(null);
        delete_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_btnMouseClicked(evt);
            }
        });
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 100, 40));

        update_btn.setBackground(new java.awt.Color(44, 58, 71));
        update_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        update_btn.setForeground(new java.awt.Color(255, 255, 255));
        update_btn.setText("UPDATE");
        update_btn.setBorder(null);
        update_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        getContentPane().add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, 100, 40));

        save_btn.setBackground(new java.awt.Color(44, 58, 71));
        save_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        save_btn.setForeground(new java.awt.Color(255, 255, 255));
        save_btn.setText("SAVE");
        save_btn.setBorder(null);
        save_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        getContentPane().add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 100, 40));

        back_btn.setBackground(new java.awt.Color(44, 58, 71));
        back_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setText("BACK");
        back_btn.setBorder(null);
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 650, 90, 40));

        subject2.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 36)); // NOI18N
        subject2.setForeground(new java.awt.Color(255, 255, 255));
        subject2.setText("LIST SUPERSTAR PLAYER ");
        getContentPane().add(subject2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        worldcup.setBackground(new java.awt.Color(52, 73, 94));
        worldcup.setFont(new java.awt.Font("Lucida Handwriting", 3, 20)); // NOI18N
        worldcup.setForeground(new java.awt.Color(255, 255, 255));
        worldcup.setText("Uefa Champions League 2022 - 2023");
        getContentPane().add(worldcup, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 440, -1));

        TabListPlayer.setAutoCreateRowSorter(true);
        TabListPlayer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TabListPlayer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        TabListPlayer.setDragEnabled(true);
        TabListPlayer.setGridColor(new java.awt.Color(0, 0, 0));
        TabListPlayer.setShowGrid(true);
        TabListPlayer.setSurrendersFocusOnKeystroke(true);
        TabListPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabListPlayerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabListPlayer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 1040, 210));

        Name_Player.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        Name_Player.setForeground(new java.awt.Color(255, 255, 255));
        Name_Player.setText("NAME PLAYER");
        getContentPane().add(Name_Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        txt_nameplayer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nameplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameplayerActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nameplayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 210, -1));

        No.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        No.setForeground(new java.awt.Color(255, 255, 255));
        No.setText("NO DATA");
        getContentPane().add(No, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txt_number.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numberActionPerformed(evt);
            }
        });
        getContentPane().add(txt_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 70, -1));

        NumberShirt.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        NumberShirt.setForeground(new java.awt.Color(255, 255, 255));
        NumberShirt.setText("NUMBER SHIRT");
        getContentPane().add(NumberShirt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        txt_nationality.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nationalityActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 210, -1));

        Age.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        Age.setForeground(new java.awt.Color(255, 255, 255));
        Age.setText("AGE PLAYER");
        getContentPane().add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        txt_club.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_club.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_clubActionPerformed(evt);
            }
        });
        getContentPane().add(txt_club, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 240, -1));

        Nationality.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        Nationality.setForeground(new java.awt.Color(255, 255, 255));
        Nationality.setText("NATIONALITY");
        getContentPane().add(Nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        search_btn.setBackground(new java.awt.Color(44, 58, 71));
        search_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        search_btn.setForeground(new java.awt.Color(255, 255, 255));
        search_btn.setText("SEARCH");
        search_btn.setBorder(null);
        search_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_btnMouseClicked(evt);
            }
        });
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        getContentPane().add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 90, 30));

        txt_no.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noActionPerformed(evt);
            }
        });
        getContentPane().add(txt_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 70, -1));

        Position.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        Position.setForeground(new java.awt.Color(255, 255, 255));
        Position.setText("POSITION");
        getContentPane().add(Position, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        txt_ageplayer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_ageplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ageplayerActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ageplayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 70, -1));

        Club_name1.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        Club_name1.setForeground(new java.awt.Color(255, 255, 255));
        Club_name1.setText("CLUB NAME");
        getContentPane().add(Club_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        txt_position.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_positionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 70, -1));

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZAINI M\\Downloads\\soccer-2699591_1280.jpg")); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private DefaultTableModel tableModel;
    private ResultSet resultSet;
    public final void showTable(){
        try {
            Connection conn = ConnectionDatabase.configDB();
            
            Object[] columnTitle = {"NO","CLUB NAME","NAME PLAYER","NATIONALITY","AGE","NUMBER SHIRT","POSITION"};
            tableModel = new DefaultTableModel(null,columnTitle);
            TabListPlayer.setModel(tableModel);
            Statement statement = conn.createStatement();
            tableModel.getDataVector().removeAllElements();
            
            resultSet = statement.executeQuery("SELECT * FROM name_player");
            while(resultSet.next()){
                Object[] data = {
                    resultSet.getString("NO"),
                    resultSet.getString("CLUB"),
                    resultSet.getString("NAME_PLAYER"),
                    resultSet.getString("NATIONALITY"),
                    resultSet.getString("AGE"),
                    resultSet.getString("NUMBER_SHIRT"),
                    resultSet.getString("POSITION")
                    
                        
                };
                tableModel.addRow(data);
            }
            System.out.println("");
            
        } catch (SQLException e) {
            System.out.println("");
            System.out.println(e);
        }
    }
    private void TabListPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabListPlayerMouseClicked
        // TODO add your handling code here:
        int baris = TabListPlayer.rowAtPoint(evt.getPoint());
        
        String no = TabListPlayer.getValueAt(baris, 0).toString();
        txt_no.setText(no); 

        String club = TabListPlayer.getValueAt(baris, 1).toString();
        txt_club.setText(club);

        String nameplayer = TabListPlayer.getValueAt(baris, 2).toString();
        txt_nameplayer.setText(nameplayer);

        String nationality = TabListPlayer.getValueAt(baris, 3).toString();
        txt_nationality.setText(nationality);

        String age = TabListPlayer.getValueAt(baris, 4).toString();
        txt_ageplayer.setText(age);

        String shirt = TabListPlayer.getValueAt(baris, 5).toString();
        txt_number.setText(shirt);
        
        String position = TabListPlayer.getValueAt(baris, 6).toString();
        txt_position.setText(position);

    }//GEN-LAST:event_TabListPlayerMouseClicked

    private void txt_nameplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameplayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameplayerActionPerformed

    private void txt_nationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nationalityActionPerformed

    private void txt_clubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_clubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_clubActionPerformed

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnMouseClicked

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Home n = new Home();
        n.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private final String regex = "\\s";
    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        try {
            String no = txt_no.getText();
            String club = txt_club.getText();
            String name_player = txt_nameplayer.getText();
            String nationality = txt_nationality.getText();
            String age = txt_ageplayer.getText();
            String number_shirt = txt_number.getText();
            String position = txt_position.getText();
            System.out.println(name_player.matches(regex));
            if ((club.isEmpty()||club.length()<3)||(name_player.isEmpty()||name_player.matches(regex))||(nationality.isEmpty()||name_player.matches(regex))||(nationality.isEmpty()||nationality.matches(regex))||(age.isEmpty()||age.matches(regex))||(number_shirt.isEmpty()||number_shirt.matches(regex))||(position.isEmpty()||position.matches(regex))||(no.isEmpty()||no.matches(regex))){
                JOptionPane.showMessageDialog(null, "DATA INVALID","Failed",JOptionPane.ERROR_MESSAGE);
            
        }else {
            String sql = "INSERT INTO `name_player`(`CLUB`, `NAME_PLAYER`, `NATIONALITY`, `AGE`, `NUMBER_SHIRT`,`POSITION`) VALUES ('" + txt_club.getText() + "','" + txt_nameplayer.getText() + "','" + txt_nationality.getText() +"','" + txt_ageplayer.getText() + "','" + txt_number.getText() + "','" + txt_position.getText() + "')";
            Connection conn = ConnectionDatabase.configDB();
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            showTable();
            JOptionPane.showMessageDialog(null, "DATA SAVED SUCCESFULLY");
            Kosongkan_Form();
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showConfirmDialog(this, e.getMessage());       
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
         try {
            String no = txt_no.getText();
            String club = txt_club.getText();
            String name_player = txt_nameplayer.getText();
            String nationality = txt_nationality.getText();
            String age = txt_ageplayer.getText();
            String number_shirt = txt_number.getText();
            String position = txt_position.getText();
            System.out.println(name_player.matches(regex));
            if ((club.isEmpty()||club.length()<3)||(name_player.isEmpty()||name_player.matches(regex))||(nationality.isEmpty()||name_player.matches(regex))||(nationality.isEmpty()||nationality.matches(regex))||(age.isEmpty()||age.matches(regex))||(number_shirt.isEmpty()||number_shirt.matches(regex))||(position.isEmpty()||position.matches(regex))||(no.isEmpty()||no.matches(regex))){
                JOptionPane.showMessageDialog(null, "DATA INVALID","Failed",JOptionPane.ERROR_MESSAGE);
                
        }else {
            String sql = "UPDATE `name_player` SET `CLUB`='"+txt_club.getText()+"',`NAME_PLAYER`='"+txt_nameplayer.getText()+"',`NATIONALITY`='"+txt_nationality.getText()+"',`AGE`='"+txt_ageplayer.getText()+"',`NUMBER_SHIRT`='"+txt_number.getText()+"',`POSITION`='"+txt_position.getText()+"' WHERE NO='"+txt_no.getText()+"'";
            Connection con = ConnectionDatabase.configDB();
            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.execute();
            showTable();
            JOptionPane.showMessageDialog(null, "DATA EDITED SUCCESSFULLY"); 
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        showTable();
        Kosongkan_Form();

    }//GEN-LAST:event_update_btnActionPerformed

    private void delete_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_btnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_btnMouseClicked

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
         try {
            String no = txt_no.getText();
            String club = txt_club.getText();
            String name_player = txt_nameplayer.getText();
            String nationality = txt_nationality.getText();
            String age = txt_ageplayer.getText();
            String number_shirt = txt_number.getText();
            String position = txt_position.getText();
            System.out.println(name_player.matches(regex));
            if ((club.isEmpty()||club.length()<3)||(name_player.isEmpty()||name_player.matches(regex))||(nationality.isEmpty()||name_player.matches(regex))||(nationality.isEmpty()||nationality.matches(regex))||(age.isEmpty()||age.matches(regex))||(number_shirt.isEmpty()||number_shirt.matches(regex))||(position.isEmpty()||position.matches(regex))||(no.isEmpty()||no.matches(regex))){
                JOptionPane.showMessageDialog(null, "DATA INVALID","Failed",JOptionPane.ERROR_MESSAGE);
                
        }else {
            String sql = "DELETE FROM `name_player` WHERE CLUB='"+ txt_club.getText() + "'";
            Connection conn = ConnectionDatabase.configDB();
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            showTable();
            JOptionPane.showMessageDialog(null, "DATA DELETED SUCCESFULLY");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        showTable();
        Kosongkan_Form();

    }//GEN-LAST:event_delete_btnActionPerformed

    private void reset_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_btnMouseClicked
        // TODO add your handling code here:
        Kosongkan_Form();
    }//GEN-LAST:event_reset_btnMouseClicked

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reset_btnActionPerformed

    private void search_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_btnMouseClicked
        // TODO add your handling code here:
        try {
            Connection conn = ConnectionDatabase.configDB();
            
            Object[] columnTitle = {"NO","CLUB NAME","NAME PLAYER","NATIONALITY","AGE","NUMBER SHIRT","POSITION"};
            tableModel = new DefaultTableModel(null,columnTitle);
            TabListPlayer.setModel(tableModel);
            Statement statement = conn.createStatement();
            tableModel.getDataVector().removeAllElements();
            
            resultSet = statement.executeQuery("SELECT * FROM name_player WHERE CLUB LIKE '%" + txt_search.getText() + "%'");
            while(resultSet.next()){
                Object[] data = {
                    resultSet.getString("NO"),
                    resultSet.getString("CLUB"),
                    resultSet.getString("NAME_PLAYER"),
                    resultSet.getString("NATIONALITY"),
                    resultSet.getString("AGE"),
                    resultSet.getString("NUMBER_SHIRT"),
                    resultSet.getString("POSITION")
                        
                };
                tableModel.addRow(data);
            }
            System.out.println("");
            
        } catch (SQLException e) {
            System.out.println("");
            System.out.println(e);
        }
        Kosongkan_Form();
    

    }//GEN-LAST:event_search_btnMouseClicked

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_btnActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void txt_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numberActionPerformed

    private void txt_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noActionPerformed

    private void txt_ageplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ageplayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageplayerActionPerformed

    private void txt_positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_positionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_positionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Superstar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Superstar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Superstar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Superstar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Superstar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JLabel Club_name1;
    private javax.swing.JLabel Name_Player;
    private javax.swing.JLabel Nationality;
    private javax.swing.JLabel No;
    private javax.swing.JLabel NumberShirt;
    private javax.swing.JLabel Position;
    private javax.swing.JTable TabListPlayer;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel bg;
    private javax.swing.JButton delete_btn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JLabel subject2;
    private javax.swing.JTextField txt_ageplayer;
    private javax.swing.JTextField txt_club;
    private javax.swing.JTextField txt_nameplayer;
    private javax.swing.JTextField txt_nationality;
    private javax.swing.JTextField txt_no;
    private javax.swing.JTextField txt_number;
    private javax.swing.JTextField txt_position;
    private javax.swing.JTextField txt_search;
    private javax.swing.JButton update_btn;
    private javax.swing.JLabel worldcup;
    // End of variables declaration//GEN-END:variables
}
